---
title: "Final_project"
author: "Josh VandenBerg"
date: "5/4/2020"
output: html_document
---
```{r}
d2018 <- read.csv("/Users/joshuavandenberg/Documents/Data Manage/2018_state.csv", skip = 12, header = FALSE, stringsAsFactors = FALSE)
d2016 <- read.csv("/Users/joshuavandenberg/Documents/Data Manage/2016_state.csv", skip = 12, header = FALSE, stringsAsFactors = FALSE)
d2014 <- read.csv("/Users/joshuavandenberg/Documents/Data Manage/2014_state.csv", skip = 12, header = FALSE, stringsAsFactors = FALSE)
d2013 <- read.csv("/Users/joshuavandenberg/Documents/Data Manage/2013_state.csv", skip = 14, header = FALSE, stringsAsFactors = FALSE)
d2012 <- read.csv("/Users/joshuavandenberg/Documents/Data Manage/2012_state.csv", skip = 15, header = FALSE, stringsAsFactors = FALSE)
d2010 <- read.csv("/Users/joshuavandenberg/Documents/Data Manage/10stall.csv", skip = 14, header = FALSE, stringsAsFactors = FALSE)
d2008 <- read.csv("/Users/joshuavandenberg/Documents/Data Manage/08stall.csv", skip = 13, header = FALSE, stringsAsFactors = FALSE)

names(d2018) <- c("State","Government_Function","FT_Employment","FT_Payroll", "PT_Employment","PT_Payroll","PT_Hours","FT_equiv_Employment","March_Employment","March_Payroll")
names(d2016) <- c("State","Government_Function","FT_Employment","FT_Payroll", "PT_Employment","PT_Payroll","PT_Hours","FT_equiv_Employment","March_Employment","March_Payroll")
names(d2014) <- c("State","Government_Function","FT_Employment","FT_Payroll", "PT_Employment","PT_Payroll","PT_Hours","FT_equiv_Employment","March_Employment","March_Payroll")
names(d2013) <- c("State","Government_Function","FT_Employment","FT_Payroll", "PT_Employment","PT_Payroll","PT_Hours","FT_equiv_Employment","March_Employment","March_Payroll")
names(d2012) <- c("State","Government_Function","FT_Employment","FT_Payroll", "PT_Employment","PT_Payroll","PT_Hours","FT_equiv_Employment","March_Employment","March_Payroll")
names(d2010) <- c("State","Government_Function","FT_Employment","FT_Payroll", "PT_Employment","PT_Payroll","PT_Hours","FT_equiv_Employment","March_Employment","March_Payroll", "Index")
names(d2008) <- c("State","Government_Function","FT_Employment","FT_Payroll", "PT_Employment","PT_Payroll","PT_Hours","FT_equiv_Employment","March_Employment","March_Payroll","Index")
d2018 <- subset(d2018, select = -c(FT_equiv_Employment, March_Employment, March_Payroll))
d2016 <- subset(d2016, select = -c(FT_equiv_Employment, March_Employment, March_Payroll))
d2014 <- subset(d2014, select = -c(FT_equiv_Employment,March_Employment, March_Payroll))
d2013 <- subset(d2013, select = -c(FT_equiv_Employment,March_Employment, March_Payroll))
d2012 <- subset(d2012, select = -c(FT_equiv_Employment,March_Employment, March_Payroll))
d2010 <- subset(d2010, select = -c(FT_equiv_Employment,March_Employment, March_Payroll, Index))
d2008 <- subset(d2008, select = -c(FT_equiv_Employment,March_Employment, March_Payroll,Index))
d2018$year <- 2018
d2013$year <- 2013
d2008$year <- 2008
d2010$year <- 2010
d2016$year <- 2016
d2012$year <- 2012
d2014$year <- 2014
full <- rbind(d2018,d2016,d2014,d2013,d2012,d2010,d2008)
full$Government_Function <- sub("Total - All Government Employment Functions","Total",full$Government_Function)
full$State <- sub("United States","US",full$State)
full$FT_Employment <- as.numeric(gsub(",","",full$FT_Employment))
full$PT_Employment <- as.numeric(gsub(",","",full$PT_Employment))
full$region <- with(full,ifelse(State %in% c("CA","AZ","AK","NM","HI","CO","WY","MT","ID","UT","NV","OR","WA","California","Arizona","Alaska","New Mexico","Hawaii","Colorado","Wyoming","Montana","Idaho","Utah","Nevada","Oregon","Washington"),"W",ifelse(State %in% c("TX","OK","AR","LA","MS","TN","AL","GA","FL","SC","NC","KY","WV","VA","MD","DE", "Texas","Oklahoma","Arkansas","Louisiana","Mississippi","Tennessee","Alabama","Georgia","Florida","South Carolina","North Carolina","Kentucky","West Virginia","Virginia","Maryland","Delaware"),"S",ifelse(State %in% c("IA","MN","ND","SD","NE","KS","MO","WI","IL","IN","MI","OH","Iowa","Minnesota","North Dakota","South Dakota","Nebraska","Kansas","Missouri","Wisconsin","Illinois","Indiana","Michigan","Ohio"),"MW",ifelse(State %in% c("ME","NH","VT","MA","RI","CT","NY","PA","NJ", "Maine","New Hampshire","Vermont","Massachusetts","Rhode Island","Connecticut","New York","Pennsylvania","New Jersey"), "NE","US")))))
total <- full[full$Government_Function == "Total",]
finance <- full[full$Government_Function == "Financial Administration",]
totalus <- total[total$State=="US",]
totalreg <- total[total$State!="US",]
totalmw <- total[total$region=="MW",]
totalS <- total[total$region=="S",]
totalW <- total[total$region=="W",]
totalne <- total[total$region=="NE",]
financeus <- finance[finance$State=="US",]
education <- full[full$Government_Function == "Education Total",]
educationus <- education[education$State=="US",]
hospital <- full[full$Government_Function == "Hospitals",]
hospitalus <- hospital[hospital$State=="US",]
judicial <- full[full$Government_Function == "Judicial and Legal",]
judicialus <- judicial[judicial$State=="US",]
police <- full[full$Government_Function == "Police Protection Total",]
policeus <- police[police$State=="US",]
highway <- full[full$Government_Function == "Highways",]
highwayus <- highway[highway$State=="US",]
mwtotal <- aggregate(FT_Employment~year,totalmw,mean)
stotal <- aggregate(FT_Employment~year,totalS,mean)
netotal <- aggregate(FT_Employment~year,totalne,mean)
wtotal <- aggregate(FT_Employment~year,totalW,mean)
mwtotalpt <- aggregate(PT_Employment~year,totalmw,mean)
stotalpt <- aggregate(PT_Employment~year,totalS,mean)
netotalpt <- aggregate(PT_Employment~year,totalne,mean)
wtotalpt <- aggregate(PT_Employment~year,totalW,mean)
```

```{r}
boxplot(totalreg$FT_Employment)
boxplot(totalreg$FT_Employment~totalreg$region)
plot(totalus$year,totalus$FT_Employment, type = "l", col = "blue")
plot(mwtotal, type = "l", col ="red")
plot(stotal, type = "l", col ="darkred")
plot(netotal, type = "l", col ="darkblue")
plot(wtotal, type = "l", col ="blue")
plot(financeus$year,financeus$FT_Employment, type = "l", col = "red")
plot(educationus$year,educationus$FT_Employment, type = "l", col = "orange")
plot(hospitalus$year,hospitalus$FT_Employment, type = "l", col = "darkred")
plot(judicialus$year,judicialus$FT_Employment, type = "l", col = "darkgreen")
plot(policeus$year,policeus$FT_Employment, type = "l", col = "darkblue")
plot(highwayus$year,highwayus$FT_Employment, type = "l", col = "darkgrey")

boxplot(totalreg$PT_Employment)
boxplot(totalreg$PT_Employment~totalreg$region)
plot(totalus$year,totalus$PT_Employment, type = "l", col = "blue")
plot(mwtotalpt, type = "l", col ="red")
plot(stotalpt, type = "l", col ="darkred")
plot(netotalpt, type = "l", col ="darkblue")
plot(wtotalpt, type = "l", col ="blue")
plot(financeus$year,financeus$PT_Employment, type = "l", col = "red")
plot(educationus$year,educationus$PT_Employment, type = "l", col = "orange")
plot(hospitalus$year,hospitalus$PT_Employment, type = "l", col = "darkred")
plot(judicialus$year,judicialus$PT_Employment, type = "l", col = "darkgreen")
plot(policeus$year,policeus$PT_Employment, type = "l", col = "darkblue")
plot(highwayus$year,highwayus$PT_Employment, type = "l", col = "darkgrey")
```
